/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Admin: () => import('#controllers/admin_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Chats: () => import('#controllers/chats_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Stores: () => import('#controllers/stores_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
