/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'storeId', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChatSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'storeId', 'updatedAt', 'userId'] as const
  $columns = ChatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['chatId', 'content', 'createdAt', 'id', 'senderType', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare chatId: number | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare senderType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderId', 'productId', 'quantity', 'unitPrice', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number | null
  @column()
  declare productId: number | null
  @column()
  declare quantity: number
  @column()
  declare unitPrice: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'customerName', 'customerPhone', 'id', 'status', 'storeId', 'totalPrice', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerName: string
  @column()
  declare customerPhone: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column()
  declare storeId: number | null
  @column()
  declare totalPrice: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'description', 'discountPrice', 'id', 'imageUrl', 'isActive', 'isAvailable', 'isFeatured', 'name', 'price', 'slug', 'stock', 'storeId', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare discountPrice: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare isAvailable: boolean | null
  @column()
  declare isFeatured: boolean | null
  @column()
  declare name: string
  @column()
  declare price: number
  @column()
  declare slug: string | null
  @column()
  declare stock: number | null
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreSchema extends BaseModel {
  static $columns = ['bannerUrl', 'createdAt', 'description', 'id', 'layoutStyle', 'logoUrl', 'name', 'slug', 'themeColor', 'updatedAt', 'userId', 'whatsappNumber'] as const
  $columns = StoreSchema.$columns
  @column()
  declare bannerUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare layoutStyle: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare themeColor: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare whatsappNumber: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'planType', 'role', 'subscriptionExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare planType: string | null
  @column()
  declare role: string | null
  @column.dateTime()
  declare subscriptionExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
